### ISSUE TITLE
[help wanted] 请问multiHeadCrossAttentionPlugin 是不支持 kv seq > 128 的情况吗？

### ISSUE THREAD

**Issue by yibolu96** [Tlntin/trt2023#1]
你好大佬，我在测试 cross attention 的时候发现这一行写死了 kv seqlen 的长度，这是为啥呢，我尝试更改这个数字之后发现会报错。以及当我真实的 kv seq len 超过128 维虽然不会报错，但是计算结果会有误。这是为啥呢？

https://github.com/Tlntin/trt2023/blob/5c46e815b65906efae255d02f6bddb3d67fea68b/plugin/multiHeadCrossAttentionPlugin/fmhcaPlugin.cpp#L290

**Comment by Tlntin** [comment]
比赛时未采用该plugin，这个是从8.6.0那边copy过来然后移植到8.6.1做一下测试而已。
官方最终给出的demo链接：https://github.com/NVIDIA/trt-samples-for-hackathon-cn/tree/master/Hackathon2023/controlnet
可以参考一下这个方案。

**Comment by yibolu96** [comment]
感谢大佬
